In [15]:
# We can initialize numpy arrays from nested Python lists, and access elements using square brackets:
import numpy as np
a = np.array([1, 2, 3])
print(type(a))
print(a)
print(a.shape)
a[1] = 5
print(a)

b = np.array([[1, 2, 4], [2, 5, 7]])
print(b.shape)
print(b)
print(type(b))
print(b[0,0], b[1,2], b[0,1])


<class 'numpy.ndarray'>
[1 2 3]
(3,)
[1 5 3]
(2, 3)
[[1 2 4]
 [2 5 7]]
<class 'numpy.ndarray'>
1 7 2
